services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    volumes:
      - dev-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=admin11
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.ml.use_auto_machine_memory_percent=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=2gb
      - cluster.routing.allocation.disk.watermark.flood_stage=2gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --output /dev/null --silent --head --fail -u elastic:admin11 http://elasticsearch:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 30

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    volumes:
      - dev-kibana:/usr/share/kibana/data
    ports:
      - 127.0.0.1:5601:5601
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=ddWPlJnM-4_CwU_UK_M=
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=xpackencryptedsavedobject123456789012
      - ELASTICSEARCH_PUBLICBASEURL=http://localhost:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://kibana:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 30


  app:
    build:
      context: ./app
    container_name: app
    volumes:
      - ./data:/data
    environment:
      - ELASTICSEARCH_PASSWORD=admin11
    depends_on:
      elasticsearch:
        condition: service_healthy
    mem_limit: 500m
    restart: on-failure

volumes:
  dev-elasticsearch:
  dev-kibana:
